:page-layout: post
:page-title: JDK8u/11/17垃圾回收器、常用JVM参数详解
:page-categories: java
:page-tags: java
include::../attributes.adoc[]
== 简介

NOTE: 本文参数解释基本都是直接来源于官方文档，部分官方文档解释较为模糊的，加入了自己的说明。

Java LTS(Long Term Support) 包括JDK8/11/17,本文只讨论三个长期支持版本

https://www.oracle.com/java/technologies/java-se-support-roadmap.html[Java LTS]

https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html#BABDJJFI[JDK8  java command for unix]

https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE[JDK11 java command]

https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html[JDK17 java command]

== 垃圾回收器
我们只讨论jdk8和jdk11文档中提到的回收器，除此以外的回收器组合方式，将不在此讨论

https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/collectors.html#sthref27[JDK8回收器]

https://docs.oracle.com/en/java/javase/11/gctuning/available-collectors.html#GUID-414C9D95-297E-4EE3-B0D9-36F158A83393[JDK11回收器]

=== Serial Collector
在JDK8/11/17中可用

单线程回收器，在小内存100MB的应用中很有用，使用-XX:+UseSerialGC启用

=== Parallel Collector
在JDK8/11/17中可用，是JDK8的默认收齐器

提供更高的吞吐量，适用于中大型数据的在多处理器运行的应用程序，使用-XX:+UseParallelGC启用。当启用该回收器时，老年代的回收默认也是并行回收的，但可以通过使用-XX:-UseParallelOldGC禁用掉。

=== Concurrent Mark Sweep (CMS) Collector
在JDK8/11中可用，CMS在JDK9中就已经标记为弃用，因此不建议在JDK11中使用

适用于大中型数据的应用程序，但相比Parallel Collector提供更低的延迟，通过-XX:+UseConcMarkSweepGC启用

=== Garbage-First Garbage Collector
在JDK8/11/17中可用，JDK11中多数系统默认使用G1回收器

适用于大中型以及超大数据的应用程序，但相比Parallel Collector提供更低的延迟，通过-XX:+UseG1GC启用

NOTE: 对于超大型内存的应用，如果想获得较低的gc停顿，G1是首选，因为G1的young gc可以是部分回收，而CMS每次都回收整个年轻代

=== Z Garbage Collector
JDK11实验特性/17中可用

可扩展低延迟垃圾收集器，并发执行所有昂贵的工作，且不会停止应用线程的运行。适用于低延迟(小于10ms)或者非常大的堆(数TB)的应用程序，通过使用-XX:+UseZGC启用

ZGC作为实验特性，从JDK11开始。如果延迟具有非常高的优先级，或者堆非常大，可以使用ZGC

NOTE: 以下提到的vm参数，如无特别说明，在JDK8/11/17中均可用，另外，所有参数说明来自于oracle官方文档。我在Openjdk官网并没有找到java command相关文档.

== gc配置
=== 内存配置
* -Xmn
+ 设置年轻代的初始和最大值。k/K表示kilobytes，m/M表示megabytes, g/G表示gigabytes。
[%hardbreaks]
比如256MB的多种表示
-Xmn256m
-Xmn262144k
-Xmn268435456
也可以使用-XX:NewSize设置初始值，-XX:MaxNewSize设置最大值
* -Xms
+
设置heap的最小值和初始值，该值必须是1024倍数，且大于1MB。k/K表示kilobytes，m/M表示megabytes, g/G表示gigabytes。
比如6MB的多种表示
-Xms6291456
-Xms6144k
-Xms6m
如果不设置此参数，则其值为初始年轻代大小和老年代的和。如果-XX:InitalHeapSize出现在-Xms后面，则初始值被-XX:InitalHeapSize覆盖。

NOTE: 官方文档中说不设置此参数，其值为初始年轻代大小和老年代的和，可是这个时候老年代大小是通过什么指定的呢？

* -Xmx
+
[%hardbreaks]
设置堆的最大值。该值必须是1024倍数且大于2MB。
例如80MB
-Xmx83886080
-Xmx81920k
-Xmx80m
等价于-XX:MaxHeapSize。
* -Xss
+
[%hardbreaks]
设置线程栈的大小 k/K表示kilobytes，m/M表示megabytes,g/G表示gigabytes。平台默认值：
Linux/ARM (32-bit): 320 KB
Linux/i386 (32-bit): 320 KB
Linux/x64 (64-bit): 1024 KB
OS X (64-bit): 1024 KB
Oracle Solaris/i386 (32-bit): 320 KB
Oracle Solaris/x64 (64-bit): 1024 KB
比如1024KB的多种表示：
-Xss1m
-Xss1024k
-Xss1048576
该参数等价于-XX:ThreadStackSize

* -XX:InitialHeapSize=size 略
* -XX:InitialRAMPercentage=percent
+
[%hardbreaks]
JVM可以使用的初始RAM占宿主机的百分比，例如5%
-XX:InitialRAMPercentage=5
* -XX:MinRAMPercentage=percent
+
JVM最小可以使用的初始RAM占宿主机的百分比
* -XX:MaxRAMPercentage=percent
+
JVM最大可以使用的初始RAM占宿主机的百分比

NOTE: 部分平台必须写成小数-XX:InitialRAMPercentage=5.0

* -XX:NewRatio=ratio
+
经验证是老年代/年轻代的比值，年轻代是分母

NOTE: 令人困惑的是，官方文档写的是young/old radio，是英语表达分母的方式不同吗？？

* -XX:InitialSurvivorRatio=ratio
+
初始存活区比例，用于ParallelGC
* -XX:SurvivorRatio
+
存活区比例

* -XX:MaxHeapSize=size 略
* -XX:MetaspaceSize=size -XX:MaxMetaspaceSize=size
+
元数据占用内存设置
[%hardbreaks]
例子
-XX:MaxMetaspaceSize=256m

* -XX:SurvivorRatio=ratio
+
eden/survivor比值

NOTE: survivor有两个，因此假设heap为100M,-XX:SurvivorRatio=8,则eden为80m，两个survivor各占10m

* -XX:TargetSurvivorRatio=ratio
+
[%hardbreaks]
例如-XX:TargetSurvivorRatio=80表示：
Survivor区从年龄为1到n的对象如果超过了80%，那么年龄阈值动态调整为n

=== 其他配置
* -XX:MaxGCPauseMillis=time
+
目标gc停顿时间。虽然官方文档未提及，但该参数应该只用于G1

* -XX:MaxTenuringThreshold=threshold
+
年龄阈值，超过此年龄的对象晋升到老年代

=== 日志
见<<#gc日志>>

== jvm日志

=== gc日志
* -verbose:gc
+
显示gc事件的信息
* -Xloggc:filename
+
[%hardbreaks]
JDK8可用，JDK11/17弃用
设置日志事件输出的文件，输出信息和-verbose:gc相似，该参数会覆盖-verbose:gc
* -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles -XX:GCLogFileSize
+
[%hardbreaks]
JDK8文档未说明（估计不可用），根据openjdk源码发现JDK8u可用(具体8u的哪个版本开始支持未确认)，JDK11/17不可用
支持按gc日志大小滚动
参考 https://stackoverflow.com/questions/35629487/can-we-rotate-gc-log-based-on-specific-time-in-jdk-8[Can we rotate GC log based on Specific Time in JDK 8?]
参考 http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/2b2511bd3cc8/src/share/vm/runtime/globals.hpp#l2447[JDK8u源码]
example：-XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=1k
该配置使得日志文件在到达1k大小时，新建新的日志文件，日志文件数最大为5个

* 仅JDK8可用的一些参数，以及在JDK11/17的替代
+
[%hardbreaks]
-XX:+PrintGC -Xlog:gc
-XX:PrintGCApplicationConcurrentTime -Xlog:safepoint
-XX:PrintGCApplicationStoppedTime -Xlog:safepoint
-XX:+PrintGCDateStamps 无替代
-XX:+PrintGCDetails -Xlog:gc*
-XX:+PrintGCTaskTimeStamps -Xlog:gc+task*=debug
-XX:+PrintGCTimeStamps 无替代
-XX:+PrintTenuringDistribution -Xlog:gc+age*=level

* JDK8文档没有，估计在JDK8u中
+
[%hardbreaks]
-XX:+PrintHeapAtGC -Xlog:gc+heap=trace
-XX:+PrintReferenceGC -Xlog:gc+ref*=debug
-XX:+SafepointTimeout 开启safepoint超时
-XX:SafepointTimeoutDelay=1000 safepoint超时时间
-XX:+PrintSafepointStatistics 打印Safepoint统计信息
-XX:PrintSafepointStatisticsCount=1 TODO

=== 其他日志
* -verbose:class
+
显示加载类的信息
* -verbose:jni
显示native方法，jni活动的信息
* -XX:+PrintCommandLineFlags
+
打印在命令行指定的jvm参数
* -XX:+PrintContainerInfo
+
[%hardbreaks]
JDK8可用，JDK11/17不可用
打印容器信息

== 容器支持
-XX:+UseContainerSupport

== 其他参数

* --dry-run
+
JDK11/17 创建虚拟机但是不执行main方法，在验证命令行参数时十分有用
* --version
+
JDK11/17 打印版本号至标准输出并退出
* -version
+
打印版本号至标准错误并退出
* -help or -?
+ 帮助
* -server
以服务器vm启动应用，启动速度变慢，但随着时间推移，运行应用速度变快
* -XshowSettings:category
显示设置并继续，可能的category值如下：
** all 显示所有设置，默认值
** locale
显示locale
** properties
显示系统属性
** vm
显示jvm设置
** system JDK11/17 on Linux: 显示宿主机或容器配置
* -XX:NativeMemoryTracking=mode
跟踪jvm native内存的使用，mode可以是以下值
** off 关闭，等同于不添加此参数
** summary 仅跟踪jvm子系统，如java heap，class，code，thread
** detail 除跟踪jvm子系统，还会跟踪 individual CallSite, individual virtual memory region，committed regions
* -XX:-UseBiasedLocking
+
禁用偏向锁。偏向锁在有大量非竞争同步的应用中可以显著加快运行速度，但某些锁定模式下会减速。

** JDK8/11默认是开启的。
** JDK17默认是禁用的。
* -XX:+HeapDumpOnOutOfMemoryError
+
发生java.lang.OutOfMemoryError导出内存快照
* -XX:HeapDumpPath=path
+
当指定-XX:+HeapDumpOnOutOfMemoryError时，配置内存快照导出的文件位置
* -XX:LogFile=path
+
hotspot日志位置