name: cache test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          /tmp/def
        key: abc  
    
    - name: test cache content
      run: |
        cat /tmp/abc || true
        echo hello >/tmp/def
        

        
