name: cache test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          /usr/bin
        key: abc  
    
    - name: test cache content
      run: |
        pwd
        cat abc || true
        echo hello>abc
        whoami
        which cat
        cat /tmp/abc || true
        cat /tmp/def || true
        echo hello >/tmp/abc
        
        

        
